spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     username: root
     password: 112167ltd
     url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
     show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
wechat:
  mpAppId: wx0be9b40c581543c7
  mpAppSecret: 548f8677c0a25b85ff599fc6e3b85437
  mchId: oYBsE1TnLzuKYdbgqK1_8Kuj_Atw
  mchKey: c976503d34ca432c601361f969fd8d85
  keyPath: /sell/h5.p12
  notiyfUrl: http://swjtu.nat300.top/sell/ay/notify