spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     username: root
     password: 123456
     url: jdbc:mysql://192.168.112.134/sell?characterEncoding=utf-8&useSSL=false
  jpa:
     show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
wechat:
  mpAppId: wx0be9b40c581543c7
  mpAppSecret: 548f8677c0a25b85ff599fc6e3b85437
  mchId: gh_51a50a709598
  mchKey: c976503d34ca432c601361f969fd8d85
  keyPath: